### ISSUE TITLE
pipewire output defaulted to a dummy sink

### ISSUE THREAD

**Issue by ghost** [Jovian-Experiments/Jovian-NixOS#88] opened 2023-05-04 01:42 UTC
ran into alot of trouble with pipewire ( most because i still us pulse) but by default all audio was going to a Dummy Sink ( what ever that is ) and Steam ui was unable to change it until i manually enabled some profiles with pactl and wpctl. I audio over hdmi still does not work could this be configured by default to save this trouble

**Comment by Ninlives** [comment] 2023-05-24 03:17
Hi, I encountered same problem today, could you please elaborate how you `manually enabled some profiles with pactl and wpctl`? Thanks!

**Comment by ghost** [comment] 2023-05-24 03:49
basically no profile was enabled so in `nix-shell -p pulsaudio` `pactl list` to show every thing then `pactl set-card-profile 42 pro-audio` (hdmi??) `pactl set-card-profile 43 pro-audio` (speaker??) not sure if your card id will be the same but I think profile names will be the same. after that every thing started working

**Comment by Ninlives** [comment] 2023-05-25 07:10
Revert alsa-ucm-conf to 1.2.8 fix the problem, there might be some regression in the new release.

**Comment by heywoodlh** [comment] 2023-05-29 17:03
> Revert alsa-ucm-conf to 1.2.8 fix the problem

For anyone in need of an example of this for a flake, here's how I did it in my flake that uses nixpkgs-unstable: https://github.com/heywoodlh/nixos-configs/commit/1efa48fe085f9b600af9c46fec032fd4cbd95601

**Comment by lheckemann** [comment] 2023-06-16 21:06
Fixed in #92!

**Comment by samueldr** [comment] 2023-06-17 04:50
Assuming fixed, since indeed it was supposed to.

If it's not, feel free to re-open (or ask me to) for the exact issue, but don't hesitate to make a precise issue for something vaguely related.

**Closed as completed by samueldr** 2023-06-17 04:50 UTC
